
allow_squash_merge: true
allow_merge_commit: true
allow_rebase_merge: true

has_issues: true
has_wiki: false
has_projects: false
has_downloads: false


labels_clean: true



labels:

  - name: bug
    description: ''
    color: d73a4a

  - name: documentation
    description: 'Improvements or additions to documentation'
    color: 0075ca

  - name: duplicate
    description: 'This issue or pull request already exists'
    color: cfd3d7

  - name: enhancement
    description: 'New feature or request'
    color: a2eeef

  - name: help wanted
    description: 'Extra attention is needed'
    color: 008672


  # Teams/Groups

  - name: ml
    color: db5cb3

  - name: infra
    color: db5cb3

  - name: dev
    color: aaffe0

  - name: it
    color: db5cb3

  # Useful labels

  - name: security
    color: db5cb3

  - name: cleanup
    color: db5cb3

  - name: refactor
    color: db5cb3

  - name: reusability
    color: db5cb3

  - name: reproducibility
    color: db5cb3

  - name: monitoring
    color: db5cb3

  - name: stability
    color: db5cb3

  - name: needs discussion
    color: 'e08155'
